apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  labels:
    app: server-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server-deployment
  template:
    metadata:
      labels:
        app: server-deployment
    spec:
      containers:
        - name: coin-server
          image: heliahashemipour/coin-server:1.0
          ports:
            - containerPort: 80
          env:
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: server-config
                  key: SERVER_PORT
            - name: COIN_NAME
              valueFrom:
                configMapKeyRef:
                  name: server-config
                  key: COIN_NAME
            - name: HOST_API
              valueFrom:
                configMapKeyRef:
                  name: server-config
                  key: HOST_API
            - name: CACHE_EXPIRE_TIME
              valueFrom:
                configMapKeyRef:
                  name: server-config
                  key: CACHE_EXPIRE_TIME
